language: csharp
solution: WeatherExplorer.sln
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test WeatherServiceTests/WeatherServiceTests.csproj
 - dotnet test WebHandlerTests/WebHandlerTests.csproj
 - dotnet test CoreHandler/CoreHandler.csproj
